storage:
  local:
    path: /tmp/ks-upgrade
download:
  globalRegistryUrl: "oci://hub.kubesphere.com.cn/kse-extensions"
  file: {}
  http:
    timeout: 20
    caBundle: ""
    insecureSkipVerify: true
  oci: {}
skipValidator: false
jobs:
  core:
    enabled: true
    priority: 10000
  network:
    enabled: false
    priority: 100
    extensionRef:
      name: "network"
      version: "1.1.0"
      namespace: "extension-network"
      chartsPath: ""
      installationMode: Multicluster
    dynamicOptions: {
      "rerun": "false"
    }
  iam:
    enabled: true
    priority: 999
  devops:
    enabled: false
    priority: 800
    extensionRef:
      version: "1.1.1"
      installationMode: Multicluster
      clusterScheduling:
      config: |
        agent:
          jenkins:
            securityRealm:
              openIdConnect:
                # The kubesphere-core api used for jenkins OIDC
                # If want to access to jenkinsWebUI, the kubesphereCoreApi must be specified and browser-accessible
                # Modifying this configuration will take effect only during installation
                # If you wish for changes to take effect after installation, you need to update the jenkins-casc-config ConfigMap，copy the securityRealm configuration from jenkins.yaml to jenkins_user.yaml, save, and wait for approximately 70 seconds for the changes to take effect.
                kubesphereCoreApi: "http://ks-apiserver:30880"
                # The jenkins web URL used for OIDC redirect
                # Modifying this configuration will take effect only during installation
                # If you wish for changes to take effect after installation, you need to update the devops-jenkins-oauthclient Secret
                jenkinsURL: "http://devops-jenkins:30180"
    dynamicOptions: {}

  storage-utils:
    enabled: false
    priority: 100
    extensionRef:
      name: "storage-utils"
      version: "1.0.0"
      namespace: "extension-storage-utils"
      config: ""
      clusterScheduling: null
      chartsPath: ""
      installationMode: Multicluster
    dynamicOptions: {
      "rerun": "false"
    }
  tower:
    enabled: false
    priority: 100
    extensionRef:
      name: "tower"
      version: "1.0.0"
      namespace: "extension-tower"
      configMap: "extension-tower-1.0.0-chart"
      configMapKey: "chart.tgz"
      configMapNamespace: "kubesphere-system"
      chartsPath: ""
      installationMode: HostOnly
      config: |
        tower:
          service:
            create: false
  kubefed:
    enabled: false
    priority: 100
    extensionRef:
      name: "kubefed"
      version: "1.0.0"
      namespace: "kube-federation-system"
      configMap: "extension-kubefed-1.0.0-chart"
      configMapKey: "chart.tgz"
      configMapNamespace: "kubesphere-system"
      chartsPath: ""
      installationMode: HostOnly
  whizard-monitoring:
    enabled: false
    priority: 100
    extensionRef:
      name: "whizard-monitoring"
      version: "1.1.0"
      installationMode: Multicluster
    dynamicOptions:
      rerun: false
      updateCrds: true
  springcloud:
    enabled: false
    priority: 100
    extensionRef:
      name: "springcloud"
      version: "1.0.0"
      namespace: "extension-springcloud"
      installationMode: Multicluster
  servicemesh:
    enabled: false
    priority: 90
    extensionRef:
      name: "servicemesh"
      version: "1.0.0"
      namespace: "extension-servicemesh"
      installationMode: Multicluster
  application:
    enabled: false
    priority: 100
    extensionRef:
      name: "openpitrix"
      version: "2.0.1"
      namespace: "extension-openpitrix"
      installationMode: HostOnly

  dmp:
    enabled: false
    priority: 80
    extensionRef:
      name: "dmp"
      version: "2.1.3"
      namespace: "extension-dmp"
      installationMode: Multicluster

  whizard-notification:
    enabled: false
    priority: 100
    extensionRef:
      name: "whizard-notification"
      version: "2.5.9"
      namespace: "kubesphere-logging-system"
      configMap: "extension-whizard-notification-2.5.9-chart"
      configMapKey: "chart.tgz"
      configMapNamespace: "kubesphere-system"
      chartsPath: ""
      installationMode: HostOnly

  whizard-alerting:
    enabled: false
    priority: 10
    extensionRef:
      name: "whizard-alerting"
      version: "1.0.3"
      installationMode: Multicluster
    dynamicOptions:
      rerun: false
      updateCrds: true

  kubeedge:
    enabled: false
    priority: 100
    extensionRef:
      name: "kubeedge"
      version: "1.13.1"
      namespace: "extension-kubeedge"
      chartsPath: ""
      installationMode: HostOnly
    dynamicOptions: {
      "rerun": "false"
    }

  whizard-events:
    enabled: false
    priority: 100
    extensionRef:
      name: "whizard-events"
      version: "1.2.0"
      namespace: "kubesphere-logging-system"
      configMap: "extension-whizard-events-1.2.0-chart"
      configMapKey: "chart.tgz"
      configMapNamespace: "kubesphere-system"
      chartsPath: ""
      installationMode: Multicluster

  gateway:
    enabled: false
    priority: 90
    extensionRef:
      name: "gateway"
      version: "1.0.2"
      namespace: "extension-gateway"
      installationMode: Multicluster

  whizard-auditing:
    enabled: false
    priority: 100
    extensionRef:
      name: "whizard-auditing"
      version: "1.2.0"
      namespace: "kubesphere-logging-system"
      configMap: "extension-whizard-auditing-1.2.0-chart"
      configMapKey: "chart.tgz"
      configMapNamespace: "kubesphere-system"
      chartsPath: ""
      installationMode: Multicluster

  whizard-logging:
    enabled: false
    priority: 100
    extensionRef:
      name: "whizard-logging"
      version: "1.2.2"
      namespace: "kubesphere-logging-system"
      configMap: "extension-whizard-logging-1.2.2-chart"
      configMapKey: "chart.tgz"
      configMapNamespace: "kubesphere-system"
      chartsPath: ""
      installationMode: Multicluster

  vector:
    enabled: false
    priority: 101
    extensionRef:
      name: "vector"
      version: "1.0.3"
      namespace: "kubesphere-logging-system"
      configMap: "extension-vector-1.0.3-chart"
      configMapKey: "chart.tgz"
      configMapNamespace: "kubesphere-system"
      chartsPath: ""
      installationMode: Multicluster

  opensearch:
    enabled: false
    priority: 100
    extensionRef:
      name: "opensearch"
      version: "2.11.1"
      namespace: "kubesphere-logging-system"
      configMap: "extension-opensearch-2.11.1-chart"
      configMapKey: "chart.tgz"
      configMapNamespace: "kubesphere-system"
      chartsPath: ""
      installationMode: Multicluster

  whizard-telemetry-ruler:
    enabled: false
    priority: 100
    extensionRef:
      name: "whizard-telemetry-ruler"
      version: "1.1.0"
      namespace: "kubesphere-logging-system"
      configMap: "extension-whizard-telemetry-ruler-1.1.0-chart"
      configMapKey: "chart.tgz"
      configMapNamespace: "kubesphere-system"
      chartsPath: ""
      installationMode: Multicluster

  whizard-telemetry:
    enabled: false
    priority: 100
    extensionRef:
      name: "whizard-telemetry"
      version: "1.2.2"
      namespace: "extension-whizard-telemetry"
      configMap: "extension-whizard-telemetry-1.2.2-chart"
      configMapKey: "chart.tgz"
      configMapNamespace: "kubesphere-system"
      chartsPath: ""
      installationMode: HostOnly

  metrics-server:
    enabled: false
    priority: 80
    extensionRef:
      name: "metrics-server"
      version: "0.7.0"
      namespace: "extension-metrics-server"
      configMap: "extension-metrics-server-0.7.0-chart"
      configMapKey: "chart.tgz"
      configMapNamespace: "kubesphere-system"
      chartsPath: ""
      installationMode: Multicluster
    dynamicOptions: {
      "rerun": "false"
    }

  hostnic:
    enabled: false
    priority: 0
#    dynamicOptions:
#      extensionNamespace:
#        labels:
#          ippool.network.kubesphere.io/ippool-0: ""
#        annotations:
#          cni.projectcalico.org/ipv4pools: '["ippool-0"]'
