kind: ConfigMap
apiVersion: v1
metadata:
  name: test-cicid-cgfhm
  ownerReferences:
    - apiVersion: devops.kubesphere.io/v1alpha3
      kind: PipelineRun
      name: test-cicid-cgfhm
      uid: 2ecdba2e-b74c-482b-91a0-fd87fb151bd3
data:
  stage: >-
    [{"displayName":"Clone
    repository","durationInMillis":23174,"id":"11","result":"SUCCESS","startTime":"2025-04-15T03:09:57Z","state":"FINISHED","type":"STAGE","edges":[{"id":"16","type":"STAGE"}],"restartable":true,"steps":[{"id":"12","displayName":"Check
    out from version
    control","type":"STEP","result":"SUCCESS","state":"FINISHED","startTime":"2025-04-15T03:09:57Z","durationInMillis":23137}]},{"displayName":"Run
    compile","durationInMillis":8202,"id":"16","result":"SUCCESS","startTime":"2025-04-15T03:10:20Z","state":"FINISHED","type":"STAGE","edges":[{"id":"25","type":"STAGE"}],"firstParent":"11","restartable":true,"steps":[{"id":"19","displayName":"Shell
    Script","displayDescription":"mvn
    compile","type":"STEP","result":"SUCCESS","state":"FINISHED","startTime":"2025-04-15T03:10:20Z","durationInMillis":8105}]},{"displayName":"Run
    test","durationInMillis":6500,"id":"25","result":"SUCCESS","startTime":"2025-04-15T03:10:28Z","state":"FINISHED","type":"STAGE","edges":[{"id":"34","type":"STAGE"}],"firstParent":"16","restartable":true,"steps":[{"id":"28","displayName":"Shell
    Script","displayDescription":"mvn clean
    test","type":"STEP","result":"SUCCESS","state":"FINISHED","startTime":"2025-04-15T03:10:28Z","durationInMillis":6410}]},{"displayName":"Run
    build","durationInMillis":7417,"id":"34","result":"SUCCESS","startTime":"2025-04-15T03:10:35Z","state":"FINISHED","type":"STAGE","edges":[{"id":"43","type":"STAGE"}],"firstParent":"25","restartable":true,"steps":[{"id":"37","displayName":"Shell
    Script","displayDescription":"mvn
    package","type":"STEP","result":"SUCCESS","state":"FINISHED","startTime":"2025-04-15T03:10:35Z","durationInMillis":7333}]},{"displayName":"Archive
    artifacts","durationInMillis":924,"id":"43","result":"SUCCESS","startTime":"2025-04-15T03:10:42Z","state":"FINISHED","type":"STAGE","firstParent":"34","restartable":true,"steps":[{"id":"44","displayName":"Archive
    the
    artifacts","type":"STEP","result":"SUCCESS","state":"FINISHED","startTime":"2025-04-15T03:10:42Z","durationInMillis":899}]}]
  status: >-
    {"artifactsZipFile":"/job/host-dev-pro8lwlb/job/test-cicid/1/artifact/*zip*/archive.zip","causes":[{"_class":"io.jenkins.blueocean.service.embedded.rest.AbstractRunImpl$BlueCauseImpl","shortDescription":"Started
    by user
    admin","userId":"admin","userName":"admin"}],"durationInMillis":149305,"enQueueTime":"2025-04-15T03:08:14Z","endTime":"2025-04-15T03:10:43Z","startTime":"2025-04-15T03:08:14Z","estimatedDurationInMillis":149305,"id":"1","organization":"jenkins","pipeline":"test-cicid","replayable":true,"result":"SUCCESS","runSummary":"stable","state":"FINISHED","type":"WorkflowRun"}
